spring:
  application:
    name: auth
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: my.service.com:8848
dubbo:
  scan:
    base-packages: com.study.shop.oauth2.controller, com.study.shop.oauth2.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://127.0.0.1
    port: 8848
server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"

business:
  oauth2:
    grant_type: password
    client_id: client
    client_secret: secret
